
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { AppProps } from "next/app";
import Header,{ BurgerMenu }  from "@/components/Header";
import { Footer } from "@/components/footer";
import { FaNeos } from "react-icons/fa";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "shop",
  description: "Generated by create next app",
  icons:{
    icon:"icon.png"

  }
};

export default function RootLayout({
  children, session
}: Readonly<{
  children: React.ReactNode, session: AppProps & never;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="wrapper">
      <Toaster/>
        <header className='header'>
        <Header/>
        </header>
        <main className="main">
        <SessionProvider session={session}>
        <BurgerMenu/>
        {children}
        </SessionProvider>
        </main>
        <footer className="footer">
        <Footer/>
        </footer>
        </div>
      </body>
    </html>
  );
}